# -*- coding: utf-8 -*-
"""
Low-level batch worker functions for the simulation engine.

This module contains the core logic for simulating a single batch of a QKD
protocol. It is designed to be executed in a separate worker process and
includes robust error handling, validation, and performance optimizations.
"""
import dataclasses
import logging
import os
import pickle
import traceback
from typing import Dict, Any

import numpy as np
# Use an alias for Generator for clarity
from numpy.random import Generator as RNG

from .params import QKDParams
from .datatypes import TallyCounts
from .protocols import MDIQKDProtocol
from .exceptions import QKDSimulationError, ParameterValidationError
from .constants import MAX_SEED_INT

__all__ = ["_simulate_quantum_part_batch", "_top_level_worker_function", "_merge_batch_tallies"]

logger = logging.getLogger(__name__)

def _check_for_termination():
    """Checks if the global termination event has been set."""
    if 'globals' in locals() and '_qkd_terminate_event' in globals():
        if globals()['_qkd_terminate_event'].is_set():
            raise InterruptedError("Termination event received by worker.")

def _simulate_quantum_part_batch(p: QKDParams, num_pulses: int, rng: RNG) -> Dict[str, Any]:
    """
    Simulates one batch of the quantum part of the protocol.

    Args:
        p: The QKDParams object containing all simulation settings.
        num_pulses: The number of pulses to simulate in this batch.
        rng: The NumPy random number generator instance for this batch.

    Returns:
        A dictionary containing the batch tally results, the total sifted
        count for the batch, and the number of pulses processed.
    """
    # Make the detector state reset conditional for more flexible simulations.
    if getattr(p, 'reset_detector_state_per_batch', True):
        p.detector.reset_state()

    _check_for_termination()
    prepared_states = p.protocol.prepare_states(num_pulses, rng)

    # Validate that prepared_states contains expected keys and lengths.
    expected_keys = ["alice_bases", "alice_bits", "alice_pulse_indices"]
    for key in expected_keys:
        if key not in prepared_states or len(prepared_states[key]) != num_pulses:
            raise QKDSimulationError(f"Protocol's prepare_states returned malformed data for key '{key}'.")

    alice_bases = prepared_states["alice_bases"]
    alice_bits = prepared_states["alice_bits"]
    misalignment_flips = rng.random(num_pulses) < p.detector.misalignment

    if isinstance(p.protocol, MDIQKDProtocol):
        photons_A = p.source.generate_photons(prepared_states["alice_pulse_indices"], rng)
        photons_B = p.source.generate_photons(prepared_states["bob_pulse_indices"], rng)
        photon_numbers = np.minimum(photons_A, photons_B)
        channel_transmittance = p.channel.transmittance**2
        ideal_outcomes_d0 = rng.random(num_pulses) < 0.5
    else:  # BB84-like protocols
        photon_numbers = p.source.generate_photons(prepared_states["alice_pulse_indices"], rng)
        channel_transmittance = p.channel.transmittance
        detector0_ideal_outcome_no_misalign = alice_bits == 0
        bob_bases_temp = rng.choice([0, 1], size=num_pulses, p=[p.protocol.bob_z_basis_prob, 1.0 - p.protocol.bob_z_basis_prob]).astype(np.int8)
        basis_match_temp = alice_bases == bob_bases_temp
        ideal_outcomes_d0 = np.where(
            basis_match_temp, np.logical_xor(detector0_ideal_outcome_no_misalign, misalignment_flips), rng.random(num_pulses) < 0.5
        )

    _check_for_termination()
    detection_results = p.detector.simulate_detection(channel_transmittance, photon_numbers, rng, ideal_outcomes_d0)
    sifted_mask, errors_mask, discarded_dc_mask = p.protocol.sift_results(num_pulses, prepared_states, detection_results, rng)

    # --- Vectorized Tallying for Performance ---
    batch_tallies = {}
    indices = prepared_states["alice_pulse_indices"]
    num_pulse_types = len(p.source.pulse_configs)

    # Add validation for indices to prevent out-of-bounds errors.
    if indices.size > 0 and (np.min(indices) < 0 or np.max(indices) >= num_pulse_types):
        raise QKDSimulationError(f"Invalid pulse indices generated by protocol. Min: {np.min(indices)}, Max: {np.max(indices)}, Num Types: {num_pulse_types}")

    # Create masks for Z and X bases
    z_basis_mask = (alice_bases == 0)
    x_basis_mask = ~z_basis_mask

    # Calculate counts for each category using a single pass where possible.
    sent_counts = np.bincount(indices, minlength=num_pulse_types).astype(np.int64)
    sifted_counts = np.bincount(indices[sifted_mask], minlength=num_pulse_types).astype(np.int64)
    errors_counts = np.bincount(indices[errors_mask], minlength=num_pulse_types).astype(np.int64)
    dc_counts = np.bincount(indices[discarded_dc_mask], minlength=num_pulse_types).astype(np.int64)

    sent_z_counts = np.bincount(indices[z_basis_mask], minlength=num_pulse_types).astype(np.int64)
    sifted_z_counts = np.bincount(indices[sifted_mask & z_basis_mask], minlength=num_pulse_types).astype(np.int64)
    errors_z_counts = np.bincount(indices[errors_mask & z_basis_mask], minlength=num_pulse_types).astype(np.int64)

    for i, pc in enumerate(p.source.pulse_configs):
        # Use standard Python ints for serialization robustness.
        t = TallyCounts(
            sent=int(sent_counts[i]),
            sent_z=int(sent_z_counts[i]),
            sent_x=int(sent_counts[i] - sent_z_counts[i]),
            sifted=int(sifted_counts[i]),
            sifted_z=int(sifted_z_counts[i]),
            sifted_x=int(sifted_counts[i] - sifted_z_counts[i]),
            errors_sifted=int(errors_counts[i]),
            errors_sifted_z=int(errors_z_counts[i]),
            errors_sifted_x=int(errors_counts[i] - errors_z_counts[i]),
            double_clicks_discarded=int(dc_counts[i]),
        )
        batch_tallies[pc.name] = dataclasses.asdict(t)

    return {"tallies": batch_tallies, "sifted_count": int(np.sum(sifted_mask)), "num_pulses": num_pulses}


def _top_level_worker_function(serialized_params: Dict, num_pulses: int, seed: int) -> Dict:
    """
    Top-level function executed by each worker process. It handles parameter
    deserialization, RNG setup, and robust error handling.
    """
    try:
        # Support loading parameters from a temp file for large configurations.
        if "params_file" in serialized_params:
            file_path = serialized_params["params_file"]
            with open(file_path, 'rb') as f:
                params_dict = pickle.load(f)
            # The orchestrator is responsible for deleting the file.
        else:
            params_dict = serialized_params

        deserialized_params = QKDParams.from_dict(params_dict)
        # Ensure seed is a valid, positive integer for the RNG.
        safe_seed = int(seed) % MAX_SEED_INT or 1
        rng = np.random.default_rng(safe_seed)
        return _simulate_quantum_part_batch(deserialized_params, num_pulses, rng)
    except (KeyboardInterrupt, InterruptedError):
        # Propagate interruptions cleanly.
        raise
    except Exception as e:
        # Provide structured error information for better debugging.
        tb = traceback.format_exc(limit=20)
        logger.error(f"Error in worker process (seed={seed}): {type(e).__name__}: {e}\n{tb}")
        # Raise a standard exception that can be caught by the orchestrator.
        raise RuntimeError(f"Worker error (seed={seed}): {type(e).__name__}: {e}") from e


def _merge_batch_tallies(overall_stats: Dict[str, TallyCounts], batch_result: Dict):
    """
    Merges tally counts from a worker batch into the main statistics object.

    This function is designed to be robust, handling both dataclass objects and
    dictionaries for the tally counts.
    """
    for name, tally_data in batch_result.get("tallies", {}).items():
        stats_obj = overall_stats.setdefault(name, TallyCounts())
        for key, val in tally_data.items():
            if hasattr(stats_obj, key):
                current_val = getattr(stats_obj, key)
                # Ensure we are adding integers.
                new_val = current_val + int(val)
                # Overflow check
                if new_val < current_val:
                    raise QKDSimulationError(f"Tally count overflow detected for '{name}.{key}'.")
                setattr(stats_obj, key, new_val)
